### ISSUE TITLE
HTML Special Characters in Attribute Values produce escaped text

### ISSUE THREAD

**Issue by Clashsoft** [fujaba/fulibTools#3]
Try the following example on fulib.org:

```markdown
# My First Scenario

There is a Label with text "<i>test</i>".
```

| l1: Label |
|-|
| text = "\&lt;i\&gt;test\&lt;/i\&gt;" |

**Comment by azuendorf** [comment]
fixed

**Comment by Clashsoft** [comment]
Somehow this bug is back after updating graphviz-java to v0.15.0. Now the `testSpecialCharsInStrings` example looks like this:

![specialChars](https://user-images.githubusercontent.com/4145923/76008571-25696100-5f10-11ea-8c0c-9eb260df2d0a.png)

When removing the escaping code in `ObjectDiagrams` completely, it looks like this:

![specialChars](https://user-images.githubusercontent.com/4145923/76008640-416d0280-5f10-11ea-8556-5f65428ff011.png)

So there seems to be no straight-forward way to make it say `<i>Greatest ever</i>`.

I'm disabling the test for now to fix the travis build.

**Comment by Clashsoft** [comment]
The change was probably introduced in Graphviz in [release 0.11.1](https://github.com/nidi3/graphviz-java/releases/tag/graphviz-java-parent-0.11.1):

> - improved escaping of special chars in dot input
